name: Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: dockrphage/devops-app:${{ github.sha }}
    - name: Update GitOps
      run: |
        git clone https://github.com/dockrphage/devops-gitops.git
        cd devops-gitops
        sed -i "s|image: dockrphage/devops-app:.*|image: dockrphage/devops-app:${{ github.sha }}|g" app/base/deployment.yaml
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image to ${{ github.sha }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
